### ISSUE TITLE
Multi-principal support?

### ISSUE THREAD

**Issue by aclark4life** [collective/collective.task#2]
Just curious if c.task can support assignment of more than one principal to a task e.g. more than one user or more than one group (assuming one user or one group is a given). And if not, how do you feel about adding support for this feature?

**Comment by aclark4life** [comment]
:zzz:

**Comment by sgeulette** [comment]
Hi @aclark4life, 
The assigned group is mono valued (responsible group). 
The assigned user is mono valued (responsible user). 
We thought about adding maybe a backup user, but from the same group. 
In our use case, we don't want to multiply the assignments to avoid decrease user responsibility (public sector). 
Do you want multivalued group to manage view or to manage modification ? For the view, another field for groups in copy can be a good solution. 
Regards
Stephan
